#!/bin/sh 
 exec /usr/sbin/chat -v                                       \
      ''      'AT'                                           \
      OK      'AT+CGMR'                                      \
      OK      'AT+CSQ'                                       \
      TIMEOUT 8                                              \
      OK      AT+CGDCONT=1,'"IP"',$APN                       \
      TIMEOUT 15                                             \
      OK      AT+MGAUTH=1,1,\"$ACCOUNT\",\"$PASSWORD\"       \
      TIMEOUT 10                                             \
      OK      ATDT$TELEPHONE                                 \
      ABORT "NO CARRIER"
